import { useState } from 'react';
import { Routes, Route, NavLink, Navigate, useNavigate } from 'react-router-dom';
import Advertisements from './pages/Advertisements/Advertisements';

const API = import.meta.env.VITE_API_URL ?? 'http://localhost:4000/api/v1';

function Login(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false); const nav=useNavigate();
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const j=await r.json();if(!r.ok)throw Error(j.error??'Login failed');localStorage.setItem('lenvora_token',j.data.token);localStorage.setItem('lenvora_admin',JSON.stringify(j.data.admin));nav('/dashboard')}catch(x){setError(x instanceof Error?x.message:'Login failed')}finally{setBusy(false)}}
 return <main className="login"><form onSubmit={submit} className="card"><div className="brand-mark">L</div><h1>Lenvora Control Center</h1><p>Private owner access</p>{error&&<div className="error">{error}</div>}<input required type="email" placeholder="Owner Gmail" value={email} onChange={e=>setEmail(e.target.value)}/><input required type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={busy}>{busy?'Signing in…':'Enter securely'}</button><small>Your password is checked on the server and is never stored in the app.</small></form></main>
}
function Layout(){const nav=useNavigate();const logout=()=>{localStorage.removeItem('lenvora_token');localStorage.removeItem('lenvora_admin');nav('/login')};const admin=JSON.parse(localStorage.getItem('lenvora_admin')||'null');return <div className="layout"><aside><div className="brand"><div className="brand-mark">L</div><div><b>Lenvora</b><small>Control Center</small></div></div><div className="owner">🔒 {admin?.email ?? 'Owner'}</div>{[['Dashboard','/dashboard'],['Advertisements','/advertisements'],['Analytics','/reports'],['Languages','/languages'],['Dictionary','/words'],['Settings','/settings']].map(([n,p])=><NavLink key={p} to={p}>{n}</NavLink>)}<button className="logout" onClick={logout}>Sign out</button></aside><section className="content"><Routes><Route path="/dashboard" element={<Dashboard/>}/><Route path="/advertisements" element={<Advertisements/>}/><Route path="*" element={<Dashboard/>}/></Routes></section></div>}
function Dashboard(){return <div><div className="hero"><div><span>OWNER MODE</span><h1>Command your Lenvora universe.</h1><p>Publish campaigns, control visibility and watch performance from one private console.</p></div><div className="hero-icon">✦</div></div><div className="stats"><div className="card"><b>Ads</b><strong>Campaign center</strong><p>Create, activate, pause and delete campaigns.</p></div><div className="card"><b>Security</b><strong>Owner only</strong><p>Protected by server-side authentication.</p></div><div className="card"><b>Distribution</b><strong>Live control</strong><p>Active ads can be delivered to the Android app.</p></div></div></div>}
export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/*" element={localStorage.getItem('lenvora_token')?<Layout/>:<Navigate to="/login" replace/>}/></Routes>}
